# Generated by Django 5.2 on 2025-04-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_username_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Доступ к премиум-функциям', verbose_name='Pro-статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Уникальный идентификатор пользователя в Telegram', null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Не обязательно для Telegram-пользователей', max_length=150, null=True, unique=True, verbose_name='Логин'),
        ),
    ]
