# Generated by Django 5.2 on 2025-04-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['deadline']},
        ),
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(default=1, max_length=50, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Статус выполнения цели'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
    ]
